# Generated by Django 6.0.3 on 2026-03-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Correo')),
                ('code', models.CharField(max_length=6, verbose_name='Código OTP')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verificado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'OTP de Email',
                'verbose_name_plural': 'OTPs de Email',
                'ordering': ['-created_at'],
            },
        ),
    ]
