# Generated by Django 6.0.3 on 2026-05-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(default='avatar_1', max_length=50, verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cedula',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Cédula / ID'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='data_policy_accepted',
            field=models.BooleanField(default=False, verbose_name='Acepta tratamiento de datos'),
        ),
    ]
