# Generated by Django 5.2.13 on 2026-04-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_icon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Icono de avatar'),
        ),
    ]
