# Generated by Django 6.0.3 on 2026-05-22 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_avatar_userprofile_cedula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_last_changed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último cambio de email'),
        ),
    ]
