# Generated by Django 6.0.3 on 2026-05-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_email_last_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(default='avatar_1', max_length=500, verbose_name='Avatar'),
        ),
    ]
