"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 6.0.3
"""

from pathlib import Path
import os

import dj_database_url
from dotenv import load_dotenv

from datetime import timedelta

# -----------------------------
# BASE / ENV
# -----------------------------
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "dev-secret-change-me")
DEBUG = os.getenv("DJANGO_DEBUG", "True").lower() == "true"
ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")

# -----------------------------
# APPS
# -----------------------------
INSTALLED_APPS = [
    "jazzmin", # Tema Dashboard moderno (debe ser el 1ro de la lista)
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    

    # Terceros
    "rest_framework",
    "rest_framework.authtoken", # Requerido por dj-rest-auth
    "corsheaders",
    "rest_framework_simplejwt",
    "django.contrib.sites",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "dj_rest_auth",
    "dj_rest_auth.registration",

    # Apps del proyecto
    "accounts",
    "catalog",
    "orders",
    "reviews",
    "inventory.apps.InventoryConfig",
    "promotions",
    "checkout",
    "shipping",
]

# -----------------------------
# MIDDLEWARE
# -----------------------------
MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CORS_ALLOWED_ORIGINS = os.getenv("CORS_ALLOWED_ORIGINS", "http://localhost:3000").split(",")

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    }
]

WSGI_APPLICATION = "config.wsgi.application"

# -----------------------------
# DATABASE
# -----------------------------
DB_ENGINE = os.getenv("DB_ENGINE", "django.db.backends.postgresql")

DATABASES = {
    "default": {
        "ENGINE": DB_ENGINE,
        "NAME": os.getenv("DB_NAME", "groob_market"),
        "USER": os.getenv("DB_USER", "groob_user"),
        "PASSWORD": os.getenv("DB_PASSWORD", "groob_password"),
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": os.getenv("DB_PORT", "5432" if "postgresql" in DB_ENGINE else "3306"),
    }
}

# -----------------------------
# AUTH / I18N
# -----------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

LANGUAGE_CODE = "es-co"
TIME_ZONE = "America/Bogota"
USE_I18N = True
USE_TZ = True

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# -----------------------------
# ALLAUTH / SOCIAL AUTH
# -----------------------------
SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

# Configuración de Allauth
ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_VERIFICATION = "none" # Ya tenemos nuestro propio sistema de OTP
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_AUTO_SIGNUP = True

# Configuración directa de Google (Evita errores de base de datos)
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": os.getenv("GOOGLE_CLIENT_ID", ""),
            "secret": os.getenv("GOOGLE_CLIENT_SECRET", ""),
            "key": ""
        },
        "SCOPE": [
            "profile",
            "email",
        ],
        "AUTH_PARAMS": {
            "access_type": "online",
        }
    }
}



# -----------------------------
# DRF
# -----------------------------
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
}

# -----------------------------
# APP CONFIG
# -----------------------------
WHATSAPP_NUMBER = os.getenv("WHATSAPP_NUMBER", "573011963515")

# Tiempo d3e vida de los tokens JWT
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=2),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
}

# ─── EMAIL CONFIG (Resend SMTP) ───────────────────────────────────────────────
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    "django.core.mail.backends.smtp.EmailBackend"
)
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.resend.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "465"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "False") == "True"
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "True") == "True"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "resend")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.getenv(
    "DEFAULT_FROM_EMAIL",
    "Groob Market <onboarding@resend.dev>"
)

# Sin password → consola (para desarrollo sin credenciales)
if not EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# ─── GROOB MARKET CONFIG ──────────────────────────────────────────────────────
WHATSAPP_NUMBER = os.getenv("WHATSAPP_NUMBER", "573011963515")
SITE_URL = os.getenv("SITE_URL", "http://localhost:3000")
GROOB_FLASH_SALE_ACTIVE = os.getenv("GROOB_FLASH_SALE_ACTIVE", "False") == "True"
GROOB_FLASH_SALE_PCT = int(os.getenv("GROOB_FLASH_SALE_PCT", "15"))

# ─── CONFIGURACION DE UI JAZZMIN (DASHBOARD) ──────────────────────────────────
JAZZMIN_SETTINGS = {
    # Títulos
    "site_title": "Admin Groob Market",
    "site_header": "Groob Market",
    "site_brand": "Groob Market ADM",
    "welcome_sign": "Bienvenido al Panel de Groob Market",
    
    # Textos bajo perfil (Opcional, busca marca de copyright)
    "copyright": "Groob Market Inc",

    # Búsqueda global (Por usuarios o lo que requiera cada app)
    "search_model": ["auth.User", "catalog.Producto", "orders.Order"],

    # Ordenar los menús del más importante (Pedidos) al menos (Auth)
    "order_with_respect_to": ["orders", "catalog", "promotions", "inventory", "shipping", "reviews", "auth"],

    # Habilitar hoja de estilos personalizada (Glassmorphism & Brand Theme)
    "custom_css": "css/admin_sidebar.css",

    # Iconos totales para todas las carpetas y subelementos usando FontAwesome
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        
        "catalog": "fas fa-store",
        "catalog.Producto": "fas fa-box-open",
        "catalog.Categoria": "fas fa-tags",
        
        "orders": "fas fa-shopping-cart",
        "orders.Order": "fas fa-shopping-bag",
        
        "inventory": "fas fa-boxes",
        "inventory.MovimientoInventario": "fas fa-pallet",
        
        "promotions": "fas fa-bullseye",
        "promotions.Coupon": "fas fa-ticket-alt",
        "promotions.SpinWheelItem": "fas fa-dharmachakra",
        
        "reviews": "fas fa-star-half-alt",
        "reviews.Review": "fas fa-comments",
        
        "shipping": "fas fa-shipping-fast",
        "shipping.TarifaEnvio": "fas fa-route",
    },
    # Ocultar apps o modelos (ej: hide_models)
    "hide_apps": [],

    # Tweaks al diseño (Oscuro por defecto para verse más pro)
    "show_ui_builder": False, # Si es True puedes jugar con colores en la interfaz tú mismo
}

JAZZMIN_UI_TWEAKS = {
    "theme": "darkly",      # 'darkly' es un tema oscuro súper elegante que combina con NextJS
    "dark_mode_theme": "darkly",
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
}