version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: groob_postgres
    restart: always
    environment:
      POSTGRES_DB: groob_market
      POSTGRES_USER: groob_user
      POSTGRES_PASSWORD: groob_password
    ports:
      - "5433:5432"
    volumes:
      - groob_db_data:/var/lib/postgresql/data

volumes:
  groob_db_data:
