# Generated by Django 6.0.3 on 2026-03-04 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'Nuevo'), ('AWAITING_CONFIRMATION', 'Pendiente confirmación'), ('CONFIRMED', 'Confirmado'), ('PACKING', 'Empacando'), ('READY_FOR_DISPATCH', 'Listo para despacho'), ('DISPATCHED', 'En ruta'), ('DELIVERED', 'Entregado'), ('CANCELED', 'Cancelado')], default='NEW', max_length=30)),
                ('payment_method', models.CharField(choices=[('COD', 'Contraentrega'), ('WHATSAPP', 'WhatsApp'), ('PAYU', 'PayU'), ('WOMPI', 'Wompi')], default='COD', max_length=20)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pendiente'), ('COD_PENDING', 'COD pendiente'), ('COD_COLLECTED', 'COD cobrado'), ('INITIATED', 'Iniciado'), ('PAID', 'Pagado'), ('FAILED', 'Fallido')], default='COD_PENDING', max_length=20)),
                ('full_name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=30)),
                ('city', models.CharField(default='Bello', max_length=60)),
                ('address', models.CharField(max_length=180)),
                ('notes', models.CharField(blank=True, max_length=250)),
                ('subtotal', models.PositiveIntegerField(default=0)),
                ('shipping_cost', models.PositiveIntegerField(default=0)),
                ('discount_total', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('unit_price', models.PositiveIntegerField()),
                ('unit_cost', models.PositiveIntegerField()),
                ('line_subtotal', models.PositiveIntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
            ],
        ),
    ]
