# Generated by Django 6.0.3 on 2026-03-24 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_image'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Ítem del pedido', 'verbose_name_plural': 'Ítems del pedido'},
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=180, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(default='Bello', max_length=60, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha del pedido'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Descuento (COP)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(max_length=120, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.CharField(blank=True, max_length=250, verbose_name='Notas / instrucciones'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Contraentrega'), ('WHATSAPP', 'WhatsApp'), ('PAYU', 'PayU'), ('WOMPI', 'Wompi')], default='COD', max_length=20, verbose_name='Método de pago'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('COD_PENDING', 'COD pendiente'), ('COD_COLLECTED', 'COD cobrado'), ('INITIATED', 'Iniciado'), ('PAID', 'Pagado'), ('FAILED', 'Fallido')], default='COD_PENDING', max_length=20, verbose_name='Estado del pago'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_cost',
            field=models.PositiveIntegerField(default=0, verbose_name='Costo envío (COP)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Nuevo'), ('AWAITING_CONFIRMATION', 'Pendiente confirmación'), ('CONFIRMED', 'Confirmado'), ('PACKING', 'Empacando'), ('READY_FOR_DISPATCH', 'Listo para despacho'), ('DISPATCHED', 'En ruta'), ('DELIVERED', 'Entregado'), ('CANCELED', 'Cancelado')], default='NEW', max_length=30, verbose_name='Estado del pedido'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.PositiveIntegerField(default=0, verbose_name='Subtotal (COP)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.PositiveIntegerField(default=0, verbose_name='Total (COP)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='line_subtotal',
            field=models.PositiveIntegerField(default=0, verbose_name='Subtotal línea (COP)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Pedido'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='qty',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_cost',
            field=models.PositiveIntegerField(verbose_name='Costo unitario (COP)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.PositiveIntegerField(verbose_name='Precio unitario (COP)'),
        ),
    ]
