# Generated by Django 6.0.3 on 2026-03-26 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_image'),
        ('orders', '0002_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address2',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Dirección secundaria / Apto / Piso'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Código de cupón'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_discount',
            field=models.PositiveIntegerField(default=0, verbose_name='% descuento cupón'),
        ),
        migrations.AddField(
            model_name='order',
            name='department',
            field=models.CharField(default='Antioquia', max_length=80, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AddField(
            model_name='order',
            name='location_lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitud GPS'),
        ),
        migrations.AddField(
            model_name='order',
            name='location_lng',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitud GPS'),
        ),
        migrations.AddField(
            model_name='order',
            name='logistics_company',
            field=models.CharField(choices=[('OWN', 'Propio (Valle de Aburrá)'), ('COORDINADORA', 'Coordinadora'), ('ENVIA', 'Envía'), ('SERVIENTREGA', 'Servientrega'), ('INTERRAPIDISIMO', 'Interrapidísimo')], default='OWN', max_length=30, verbose_name='Empresa logística'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Número de guía'),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(default='', max_length=200, verbose_name='Nombre del producto (snapshot)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_sku',
            field=models.CharField(default='', max_length=80, verbose_name='SKU (snapshot)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Dirección principal'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(default='Medellín', max_length=80, verbose_name='Ciudad o municipio'),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Instrucciones adicionales'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('COD_PENDING', 'COD pendiente'), ('COD_COLLECTED', 'COD cobrado'), ('PAID', 'Pagado'), ('FAILED', 'Fallido')], default='COD_PENDING', max_length=20, verbose_name='Estado del pago'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='Teléfono / WhatsApp'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', '🆕 Recibido'), ('CONFIRMED', '✅ Confirmado'), ('PACKING', '📦 Empacando con amor'), ('ON_THE_WAY', '🛵 En camino a ti'), ('LOGISTICS', '🚚 En manos de la empresa logística'), ('DELIVERED', '🎉 Entregado con éxito'), ('CANCELED', '❌ Cancelado')], default='NEW', max_length=30, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_cost',
            field=models.PositiveIntegerField(default=0, verbose_name='Costo unitario (COP)'),
        ),
    ]
