# Generated by Django 6.0.3 on 2026-04-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_address2_order_coupon_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', '🆕 Pedido Realizado'), ('CONFIRMED', '✅ Confirmado'), ('PACKING', '📦 Empacando con amor'), ('ON_THE_WAY', '🛵 En camino a ti'), ('LOGISTICS', '🚚 En manos de la empresa logística'), ('DELIVERED', '🎉 Entregado con éxito'), ('CANCELED', '❌ Cancelado')], default='NEW', max_length=30, verbose_name='Estado'),
        ),
    ]
