# Generated by Django 6.0.3 on 2026-05-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cedula',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Cédula / ID'),
        ),
    ]
