# Generated by Django 6.0.3 on 2026-05-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='wompi_transaction_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='ID de Transacción Wompi'),
        ),
    ]
