# Generated by Django 6.0.3 on 2026-03-24 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifaenvio',
            name='dias_habil',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 = mismo dia, 3 = tres dias habiles, etc.', verbose_name='Dias habiles de entrega'),
        ),
    ]
