# Generated by Django 6.0.3 on 2026-04-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_alter_tarifaenvio_dias_habil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarifaenvio',
            options={'ordering': ['zona', 'municipio'], 'verbose_name': 'Tarifa de envío', 'verbose_name_plural': 'Tarifas de envío'},
        ),
        migrations.RemoveField(
            model_name='tarifaenvio',
            name='costo',
        ),
        migrations.RemoveField(
            model_name='tarifaenvio',
            name='dias_habil',
        ),
        migrations.RemoveField(
            model_name='tarifaenvio',
            name='tipo',
        ),
        migrations.AddField(
            model_name='tarifaenvio',
            name='precio',
            field=models.PositiveIntegerField(default=18000, verbose_name='Precio de envío (COP)'),
        ),
        migrations.AddField(
            model_name='tarifaenvio',
            name='tiempo',
            field=models.CharField(default='3 – 5 días hábiles', max_length=50, verbose_name='Tiempo estimado'),
        ),
        migrations.AddField(
            model_name='tarifaenvio',
            name='zona',
            field=models.CharField(choices=[('ZONA_1', 'Zona 1 — Bello (0-5 km)'), ('ZONA_2', 'Zona 2 — Medellín (5-20 km)'), ('ZONA_3', 'Zona 3 — Valle de Aburrá (20-40 km)'), ('ZONA_4', 'Zona 4 — Antioquia cercana (40-80 km)'), ('ZONA_5', 'Zona 5 — Antioquia lejana (80-200 km)'), ('ZONA_6', 'Zona 6 — Nacional (+200 km)')], default='ZONA_6', max_length=10, verbose_name='Zona de distancia'),
        ),
        migrations.AlterField(
            model_name='tarifaenvio',
            name='municipio',
            field=models.CharField(max_length=100, unique=True, verbose_name='Municipio / Ciudad'),
        ),
    ]
