# Generated by Django 6.0.3 on 2026-03-20 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('percent', models.PositiveSmallIntegerField(verbose_name='Descuento (%)')),
                ('is_used', models.BooleanField(default=False, verbose_name='Usado')),
                ('first_purchase_only', models.BooleanField(default=True, verbose_name='Solo primera compra')),
                ('expires_at', models.DateTimeField(verbose_name='Expira el')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cupón',
                'verbose_name_plural': 'Cupones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpinLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spun_at', models.DateTimeField(auto_now_add=True, verbose_name='Giró el')),
                ('percent_awarded', models.PositiveSmallIntegerField(default=0, verbose_name='Descuento asignado (%)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spin_log', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ruleta - Giro',
                'verbose_name_plural': 'Ruleta - Giros',
            },
        ),
    ]
