# Generated by Django 6.0.3 on 2026-04-07 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='qty_after',
            field=models.IntegerField(default=0, editable=False, verbose_name='Stock Después'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='qty_before',
            field=models.IntegerField(default=0, editable=False, verbose_name='Stock Antes'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario responsable'),
        ),
    ]
